### ISSUE TITLE
Load by default in Jupyter notebooks?

### ISSUE THREAD

**Issue by juliohm** [stevengj/SoftGlobalScope.jl#15]
Could you please clarify the model in Jupyter? If I start a notebook by typing `jupyter notebook` on the shell, will SoftGlobalScope.jl be loaded in Julia sessions? Are we assuming here that the `SoftGlobalScope.jl` rules will only apply if I start a notebook from Julia with `using IJulia; notebook()` or something similar?

**Comment by stevengj** [comment]
SoftGlobalScope is enabled by default in every Ijulia notebook, regardless of how Jupyter is launched

**Comment by juliohm** [comment]
It is not happening on my laptop though. IJulia 1.14.x I think. O tried
updating. I will retry to see if I missed something
