### ISSUE TITLE
lack of soft scope inside macro calls

### ISSUE THREAD

**Issue by juliohm** [stevengj/SoftGlobalScope.jl#16]
As discussed in https://github.com/timholy/ProgressMeter.jl/issues/119, there seems to be an issue within Jupyter notebooks when the Progressmeter.jl package is used. Maybe a PR in that repository would help the maintainers there to keep up to date with the new hard vs. soft scoping rules.

cc: @timholy

**Comment by stevengj** [comment]
SoftGlobalScope doesn't work inside macro calls, e.g. in
```jl
@showprogress 1 "Simulating..." for i=1:10
    ...
end
```
it doesn't touch the macro arguments.

We certainly can't do anything before macro expansion here, because the macro might rewrite the code arbitrarily.    I don't know if it is feasible to call `macroexpand` ourselves inside a macro.

(I seem to recall @timholy saying that rewriting macro calls would also screw up Rebugger.)

**Comment by timholy** [comment]
Macros (for all their goodness) make life more complex, and I suffered from an embarrassingly large number of Revise/Rebugger bugs with regards to when to expand them and the interaction of that choice with regards to the expression-cache and lookup-by-signature Dicts that Revise maintains (https://github.com/timholy/Revise.jl/issues/174, https://github.com/timholy/Revise.jl/issues/176, https://github.com/timholy/Revise.jl/issues/181, https://github.com/timholy/Revise.jl/issues/183, https://github.com/timholy/Revise.jl/issues/191). But I may have nailed the most pressing bugs by now, and I'm not sure there are any fundamental obstacles (just complexity). Though perhaps I'm not remembering the issue exactly.

**Comment by juliohm** [comment]
I am not remembering the last time I encountered this issue. I will close it since it is not that important.

**Comment by cossio** [comment]
I am encountering this issue now. Maybe reopen?

Though if I understand correctly, this won't be important soon, with the new scoping of Julia 1.5. Can someone confirm? If that's the case then there is definitely no point in reopening.

**Comment by stevengj** [comment]
With Julia 1.5, the `softscope` transformation in this package just calls through to the `REPL.softscope` function, which handles macros.  e.g. the `@showprogress` example works:
```jl
julia> s = 0
0


julia> @showprogress 1 "Simulating..." for i=1:10
           s = s+1
           sleep(1)
       end
Simulating...100%|████████████████████████████████████████████████| Time: 0:00:10


julia> s
10
```
