### ISSUE TITLE
softscope_include_string cannot define modules

### ISSUE THREAD

**Issue by stevengj** [stevengj/SoftGlobalScope.jl#3]
From JuliaLang/IJulia.jl#722:

```jl
julia> softscope_include_string(Main, "module Foo; end")
ERROR: syntax: "module" expression not at top level
Stacktrace:
 [1] eval at ./boot.jl:319 [inlined]
 [2] softscope_include_string(::Module, ::String, ::String) at /Users/stevenj/.julia/dev/SoftGlobalScope/src/SoftGlobalScope.jl:105
 [3] softscope_include_string(::Module, ::String) at /Users/stevenj/.julia/dev/SoftGlobalScope/src/SoftGlobalScope.jl:101
 [4] top-level scope at none:0
```

The problem is that, as hack to parse a whole file's expression at once (in order to preserve line numbers), `softscope_include_string` currently wraps it in `begin ... end`, but this is not allowed for modules.

The solution would be to just use `Meta.parse` to parse and evaluate one expression at a time.  The trick is to figure out how to do this while preserving the line-number information.

**Comment by stevengj** [comment]
Basically, we want to emulate the [behavior of `jl_parse_eval_all`](https://github.com/JuliaLang/julia/blob/804d12ebe3801f7faf8cea234ffe6ec2452443c8/src/ast.c#L811-L912), but transforming each expression as it is parsed.

**Comment by dawbarton** [comment]
This might not be necessary - I'm just about to add a PR for softscoping multiple statements that might help.

**Comment by stevengj** [comment]
@dawbarton, the problem is the line `Base.parse_input_line("begin; "*code*"\nend\n", filename=filename)`, which your PR doesn't alter.

**Comment by dawbarton** [comment]
Yes, I just realised that. Sorry for the noise.
